# Generated by Django 3.1.5 on 2021-09-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
