# Generated by Django 3.1.5 on 2021-11-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
    ]
