# Generated by Django 3.1.5 on 2021-11-16 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerceapp', '0004_remove_payment_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('orderid', models.CharField(default='', max_length=200)),
                ('paymentid', models.CharField(default='', max_length=200)),
                ('totalprice', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('on the way', 'on the way'), ('delievered', 'delievered')], default='Accepted', max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
