# Generated by Django 3.1.5 on 2021-11-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_userproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail')], default='fail', max_length=200),
        ),
    ]
