# Generated by Django 3.1.5 on 2021-11-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_auto_20211116_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('fail', 'fail')], max_length=200),
        ),
    ]
